### ISSUE TITLE
How can I vary the strength of an edit?

### ISSUE THREAD

**Issue by thaoshibe** [Hzzone/AdaTrans#1]
Hello, thanks for your interesting work!
I have a question about strength of an edit (For example, in the teaser figure, where we can edit "old" attribute by specific age-number: 10 years old, 70+ years old, etc.)
![Screen Shot 2023-09-27 at 12 03 18 PM](https://github.com/Hzzone/AdaTrans/assets/22058807/90822dbd-8367-4cfb-80f6-19e73624b2e8)

As far as I understand, we need to manually edit the Facial Attribute vector $a$.
For example, given an initial image $I$ with corresponding facial attribute $a= [age, glasses,...] =[10, 1, ...]$.
I want to edit image $I$ into image $I'$ which age = 70.

Then I will have to edit the corresponding facial attribute $a$ into $a'= [age, glasses,...] =[70, 1, ...]$. Is that correct?

![Screen Shot 2023-09-27 at 12 01 45 PM](https://github.com/Hzzone/AdaTrans/assets/22058807/bdbda6d9-7033-40d7-9d4b-e4c3507f025c)

Looking forward for your response. Thank you!

**Comment by Hzzone** [comment]
I do not use absolute value as the condition for age attributes. Instead, we use the ordinal/one-hot encoding, please see https://github.com/Hzzone/AdaTrans/blob/717c15f7a8ef8c5728f37a5f6f01bd6b0790771d/webui/app.py#L207C23-L207C23

One may change the corresponding encoding to edit specific age, eg, [0, ..., 0] for 10- years old, and [1, 1, ..., 1] for 70+

**Comment by thaoshibe** [comment]
Thanks for your quick response!
I understand it better now.

So according to the paper:
> "For the fixed attribute classifier, we trained the last linear layer of ResNet-50 [15] on the binary attributes of CelebA dataset [28] and the discrete age labels of FFHQ from [30]".

Is it true that:
1. For age: AdaTrans can edit **7 types** of discrete age labels (0-6) (This is trained on FFHQ's age attributes)
2. For other attributes (e.g., eyeglasses, wavy hair): AdaTrans can edit 40 types of **binary** edits (This is trained on [CelebA's 40 binary attributes](https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html)).

Can you please verify if my above statements are correct? I do want to understand the paper better! Thank you so much!

**Comment by Hzzone** [comment]
You are right.
