### ISSUE TITLE
 det_faces = face_detector(input_img, 1)

### ISSUE THREAD

**Issue by xLuge** [Hzzone/AdaTrans#2]
the det_face is always None . do you have any suggestions?

**Comment by Hzzone** [comment]
Could you post your test image?

**Comment by xLuge** [comment]
> Could you post your test image?

the rect cannot be detected in any ffhq picture. 
![Uploading 00065_0.jpg…]()

**Comment by xLuge** [comment]
![00065_0](https://github.com/Hzzone/AdaTrans/assets/37794367/323ee6b0-8e15-4527-8ab4-995788eb2a1c)

**Comment by Hzzone** [comment]
Hi, I have tested this image on my colab demo, the face has been detected and it works like the below:
<img width="1074" alt="image" src="https://github.com/Hzzone/AdaTrans/assets/19267349/df21c38e-4ee7-4dbd-8fde-6864ec44008d">

**Comment by xLuge** [comment]
> Hi, I have tested this image on my colab demo, the face has been detected and it works like the below: <img alt="image" width="1074" src="https://user-images.githubusercontent.com/19267349/280680857-df21c38e-4ee7-4dbd-8fde-6864ec44008d.png">
the output is  always 'mmod_rectangles[]' 
<img width="673" alt="企业微信截图_d95038c6-2466-4d7a-a3dd-1956988fb341" src="https://github.com/Hzzone/AdaTrans/assets/37794367/37b0f055-b8f7-4794-861f-ce72927e7e65">


<img width="174" alt="image" src="https://github.com/Hzzone/AdaTrans/assets/37794367/c17dfd89-d415-471d-bfb9-9f3c42c4acce">

**Comment by Hzzone** [comment]
<img width="837" alt="image" src="https://github.com/Hzzone/AdaTrans/assets/19267349/0cb45083-3b87-4620-be96-45a536d8be8f">

**Comment by xLuge** [comment]
Strange, my code remains the same as yours and is still None.  when i run the app.py, none too.
<img width="745" alt="企业微信截图_61382201-b7cc-4a14-bf15-a5413daf052e" src="https://github.com/Hzzone/AdaTrans/assets/37794367/87278fab-00f4-4e1a-9d8d-1c29412d2568">

**Comment by xLuge** [comment]
low torch version seems to solve this problem.
