### ISSUE TITLE
Seeking help regarding the issue of being unable to download the pre-trained IResNet model

### ISSUE THREAD

**Issue by fanzhangnc** [Hzzone/AdaTrans#3]
![1699622740273](https://github.com/Hzzone/AdaTrans/assets/150440809/33c76901-8e4e-4c1e-97d0-fdd91542c186)

ps: The download link https://sota.nizhib.ai/pytorch-insightface/iresnet34-5b0d0e90.pth for the pre-trained IResNet model is invalid, causing an HTTP Error 404: Not Found. Could you please provide alternative methods to obtain the IResNet model. I really appreciate for your help and look forward to your reply!

**Comment by Hzzone** [comment]
I have uploaded these pre-trained models to https://drive.google.com/drive/folders/1T5y6l5Byl4pDzFCcDRXDOmmXde2HGg5U?usp=sharing

**Comment by fanzhangnc** [comment]
Thank you for your feedback so quickly, I have tried the pretrained model which is really helpful. Much appreciated:)
