### ISSUE TITLE
Separate models for each attribute or a single model for all attributes?

### ISSUE THREAD

**Issue by fanzhangnc** [Hzzone/AdaTrans#4]
Hello, thank you very much for providing the pre-trained models, which are very helpful. 

I have a few additional questions. Firstly, I am unsure of the meaning of this sentence in section 4.2.1 of the paper: "Note that we train all attributes presented in Fig. 4 in a unified model". Aren't binary attributes supposed to be trained separately from one-hot conditions like hair color or style? Could you please give me some hints about how you conduct the training when performing the experiment?

![895919b6bceb232e874abd624ea5d3fa_4_Figure_4_-843180584](https://github.com/Hzzone/AdaTrans/assets/150440809/4f7e8596-8520-46a1-afcc-23093a2acbcf)

Secondly, I can't find the code for some experiments mentioned in the paper, such as "Editing with 128 labeled samples only" and "nonlinear editing with a fixed step size at each step". Could you please provide the code or give me some guidance on the code implementation for these specific experiments?

Thank you very much, and have a great day :)

My E-mail: fanzhang@email.ncu.edu.cn

**Comment by Hzzone** [comment]
1, An example of training two attributes in single model can be `python train.py --max_steps 10 --changes 15 39 --keeps 20 --run_name 15_39`. Separate models can be trained too, and see https://github.com/Hzzone/AdaTrans/blob/717c15f7a8ef8c5728f37a5f6f01bd6b0790771d/webui/app.py#L202  how to combine their results.
2. Randomly select 128 labeled samples from celeba-hq for each attribute, 64 positives and 64 negatives, and train a classifier. Fixed step size denotes st=1 in Eqs 3 and 4.
