### ISSUE TITLE
 Two classifiers with different weights?

### ISSUE THREAD

**Issue by fanzhangnc** [Hzzone/AdaTrans#5]
Hello, thank you so much for your previous help; it gives me a deeper understanding of the paper.

I'm confused by these two sentences in section 4.1 of the paper: 

"For the fixed attribute classifier, we trained the last linear layer of ResNet-50 [15] on the binary attributes of the CelebA dataset [28] and the discrete age labels of FFHQ from [30]. We train another classifier from scratch for better classification performance and obtain the attribute labels of the FFHQ dataset".

1.Does that mean the weights of the classifier used to generate attribute labels are different from the one computing the Lmi loss?
![895919b6bceb232e874abd624ea5d3fa_2_Figure_2_755637297](https://github.com/Hzzone/AdaTrans/assets/150440809/9d55a965-e51e-4e57-84cf-2ad6e42822ed)

2.Which classifier is the provided "Train the classifier" code aim to train? And could you please give me some guidance on the code implementation for training the other classifier?
![image](https://github.com/Hzzone/AdaTrans/assets/150440809/2810a28f-7cc7-4d7d-a638-80b960e9df5b)

3.In the "Editing with limited labeled data" experiment, are the attribute labels for the FFHQ dataset also generated by a classifier trained only on 128 samples, or by a classifier trained normally on the CelebA dataset?

Thank you very much, and have a great day :)

My E-mail: fanzhang@email.ncu.edu.cn

**Comment by Hzzone** [comment]
1. The classifier Q is the same for the network. We employ a resnet34 for our network and another resnet50 only for evaluation. See https://github.com/Hzzone/AdaTrans/blob/master/evaluation.ipynb
2. https://github.com/Hzzone/AdaTrans/blob/master/training/train_realnvp_and_classifier.ipynb presents how to train the classifier. You only need change:
```python
# Binary Classifier
# backbone = 'r50'
backbone = 'r34'
```
3. This classifier is trained on CelebA.

**Comment by fanzhangnc** [comment]
Thank you so much for your quick response, which is very helpful.

So, based on your previous answer:

"Randomly select 128 labeled samples from celeba-hq for each attribute, 64 positives and 64 negatives, and train a classifier".

Is it true that:

1.In the "Editing with limited labeled data" experiment, though a new classifier needs to be trained with the 128 labeled data from celeba-hq, the labels of the FFHQ dataset (all_preds) are still obtained from the classifier trained on the entire celebA dataset of 202,599 face images. 

2.The maximum step  should be set to 5 instead of 10, just like in other experiments.
![image](https://github.com/Hzzone/AdaTrans/assets/150440809/7b6060cd-e3db-4281-8bca-1085e32fb880)

Could you please verify if my statements are correct? I do want to understand the paper better! Thank you very much!

**Comment by Hzzone** [comment]
1. I have checked the code. I have trained the classifier with only 128 samples and then used this classifier to re-generate the predictions for FFHQ.
2. You could. 10 achieves better results without many costs.

**Comment by fanzhangnc** [comment]
Hello, many thanks for your assistance.

Based on your previous guidance, I trained a classifier with limited labeled samples and used it to generate labels for FFHQ. Then, I trained attributes like glasses, gender, and age using this classifier and the generated labels. I tested the model using the evaluation methods provided in `evaluation.ipynb`. However, the results differ somewhat from what is described in your paper:
![1703310448230](https://github.com/Hzzone/AdaTrans/assets/150440809/febb8984-3121-4fe3-93f6-74f4daabe8a6)

1. Using 128 labeled samples, the Attribute Preservation is only 84% when the Editing Accuracy reaches 99%, rather than the 95% presented in the paper.
![128](https://github.com/Hzzone/AdaTrans/assets/150440809/a0ffa099-f553-48df-b319-9b5d24cce6ef)

2. Using 32 labeled samples, the Editing Accuracy can reach a maximum of only around 12.5%.
![32](https://github.com/Hzzone/AdaTrans/assets/150440809/215e1771-1ee0-4486-805d-6e5f51f6d0c1)

Could you please give me some hints about possible reasons why I am unable to reproduce the results?

Thank you very much, and have a great day :)

**Comment by Hzzone** [comment]
If you want, please send an email to zhizhonghwang@gmail.com

I will give you all related code that reproduces this experiment. But, it can be only a reference, and may not fit the public code.
